Support nocov comment at the end of a line
colszowka/simplecov pull request #1068
Opened 2023-08-28 18:32 UTC by cyberdelia

Support `nocov` comments at the end of a line to mark it as irrelevant, it's a bit less verbose that block to ignore some benign things.

```ruby
case value
when String
  StringFilter
when Array
  ArrayFilter
else
  raise "Absurd case" # :nocov: 
end
```

2023-08-29 20:59 UTC, cyberdelia commented
cc/ @amatsuda

2023-10-10 19:21 UTC, cyberdelia commented
Rebased.

2023-12-28 07:06 UTC, cyberdelia commented
Freshly rebased.

2024-04-19 01:00 UTC, cyberdelia commented
Freshly rebased!

cc/ @PragTob

2024-10-30 15:07 UTC, will commented
@amatsuda please consider this pull request

2026-04-04 04:58 UTC, sferik requested changes
I have a bit of feedback but support this feature overall.

Somewhat related: as we approach a 1.0.0 release, I was considering changing the block syntax to be more explicit. Something like:

```ruby
case coverage_criterion
when :line   then compute_line
when :branch then compute_branch
when :method then compute_method
else
  # coverage:disable
  raise "Unknown criterion: #{coverage_criterion}"
  # coverage:enable
end
```

If that was the block syntax, presumably we’d want the inline syntax to match:

```ruby
case coverage_criterion
when :line   then compute_line
when :branch then compute_branch
when :method then compute_method
else
  raise "Unknown criterion: #{coverage_criterion}" # coverage:disable
end
```

This seems as good a place as any to debate making this change.

2026-04-04 04:58 UTC, sferik commented on lib/simplecov/lines_classifier.rb
> +      /#(\s*)(:#{SimpleCov.nocov_token}:)(\s*)$/o
This matches any line containing `# :nocov:` anywhere, including the block markers themselves (which are comment-only lines like `# :nocov:`). That means `no_cov_block?` lines will also match `no_cov_line?`. In `classify`, this doesn’t currently cause an issue because the `if no_cov_block?` branch is checked first, but it’s fragile. The regex should exclude comment-only lines to be precise:

```suggestion
      /\S.*#\s*:#{SimpleCov.nocov_token}:\s*$/o
```

2026-04-04 04:58 UTC, sferik commented on lib/simplecov/lines_classifier.rb
> +    def self.no_cov_block
You’ve renamed the public method `no_cov_line`, which external code may call, and the new `no_cov_line` has different semantics. This is a breaking change for anyone calling `LinesClassifier.no_cov_line?` or using the regex directly. A less disruptive approach would be to keep `no_cov_line` as-is and add `no_cov_inline` for the new behavior.

2026-04-04 04:58 UTC, sferik commented on spec/lines_classifier_spec.rb
> +            "puts 'Not relevant till the end' # :nocov:",
I would add a separate, focused test for interactions between inline markers and blocks, instead of making this (already complex) test more complex. There are also a few other edge cases worth testing (e.g. inline `# :nocov:` comment inside a block).

2026-04-04 06:32 UTC, PragTob commented
@sferik I like the idea of beginning and end comments, makes diagnosis easier 👌 

As for one line/in-line comments I can see the appeal but there's a lot of edge cases to consider (as Erik pointed out) and iirc the lines classifier has been a source of performance degradation in the past - those together make me wonder how much of this we _need_. 

The other thing to consider here is how this plays with branch coverage/other coverage types in general.

2026-04-04 17:28 UTC, sferik commented
> The other thing to consider here is how this plays with branch coverage/other coverage types in general.

Yes. Since https://github.com/simplecov-ruby/simplecov/pull/1161 we also now support method coverage, in addition to line and branch coverage.

Perhaps we should have more granular disabling like:
```ruby
# coverage:disable:line
# coverage:disable:branch
# coverage:disable:method
# coverage:disable (disables all three)
```

These should work in both block and inline form.

@PragTob What do you think?

PS: I realize we’re bikeshedding the heck out of this PR, which is more narrowly scoped, but—if we’re going to make API changes before the 1.0 release—I want to make sure we get this right.

2026-05-01 20:55 UTC, PragTob commented
@sferik yeah, changes live on in the API and for future support so I believe it's worth considering/talking about.

I don't think we need different sub types of coverage disable/enable. The most common use case for coverage disable is "these lines of code do not matter" and I don't think the type of coverage makes a difference there. I should have been more explicit, but the question of how does it play with other types of coverage is mote like: 

I'm ignoring one line of code inside a branch - will the branch be counted? I'm ignoring all but one line of code inside a branch - will it be counted? I'm ignoring the condition that causes a branch, will the branch be counted?

I personally think it's fine to say: Undefined behavior, you did this to yourself. If I'd wish for anything, as long as any line inside a branch is not ignored, the branch shouldn't be ignored. But I'm not sure how much code would be needed to support that or in fact not sure what the current behavior is. 

But people will complain that it works different from what they imagine :)

2026-05-04 19:35 UTC, sferik commented
I just chatted with @PragTob and we decided on the following comment syntax:

```ruby
# simplecov:disable line
# simplecov:disable method
# simplecov:disable branch
# simplecov:disable method,branch         <- disables method and branch coverage
# simplecov:disable                       <- disables all three
# simplecov:enable                        <- enables all three
raise "Absurd case" # simplecov:disable   <- just disables this line, no need to re-enable
```

2026-05-05 16:31 UTC, sferik commented
Resolved by https://github.com/simplecov-ruby/simplecov/pull/1179.

2026-05-05 16:31 UTC, closed without merging